### ISSUE TITLE
npm package on package.json

### ISSUE THREAD

**Issue by jsappme** [remixz/messenger-bot#70] opened 2017-03-19 20:38 UTC
if I put on my package.json: "messenger-bot": "2.4.0", I get weird error 
so I have to write: "messenger-bot": "github:remixz/messenger-bot",

any idea why?

**Comment by Maluen** [comment] 2017-04-27 14:47
This might be a duplicate of https://github.com/remixz/messenger-bot/issues/60

**Comment by eXeDK** [comment] 2018-07-01 21:02
NPM version 2.5.0 are now out

**Closed by eXeDK** 2018-07-01 21:02 UTC
